### ISSUE TITLE
Soporte versiones Chrome superiores a 114

### ISSUE THREAD

**Issue by albertotb** [gerardcl/renfe-cli#173]
**Describe the bug**
Debido a un cambio donde se almacenan los drivers de Chrome, la librería solo es compatible con Chrome 114 o inferior.

**To Reproduce**
Instalar la versión estable de Chrome a 2023-09-04 (116.0.5845) y ejecutar la aplicación. El error es:

```
ERROR:root:There is no such driver by url https://chromedriver.storage.googleapis.com/LATEST_RELEASE_116.0.5845
```

**Environment (please complete the following information):**
 - OS: Ubuntu 
 - Version: 22.04

**Additional context**
Parece que los desarrolladores de Chrome cambiaron la localización de los drivers. Más contexto  aquí: https://chromedriver.chromium.org/getting-started
Actualizar Selenium y retocar ligeramente el código parece una posible solución:
https://stackoverflow.com/questions/76724939/there-is-no-such-driver-by-url-https-chromedriver-storage-googleapis-com-lates

En mi caso, he probado a descargar el driver manualmente de https://googlechromelabs.github.io/chrome-for-testing/ y añadirlo al `PATH`, sin éxito. Si ha funcionado hacer downgrade de la versión de Chrome a la 114: 
- https://makandracards.com/makandra/486433-how-to-downgrade-google-chrome-in-ubuntu
- https://www.ubuntuupdates.org/package/google_chrome/stable/main/base/google-chrome-stable?id=202706&page=2

**Comment by gerardcl** [comment]
hola @albertotb ! tengo pensado hacer migración completa a Rust de este CLI en algun momento, por ahora no seguiré el mantenimiento con python de forma estable, mi expectativa por ahora es que todos vayamos aportando arreglos al código, adelante con propuestas/PRs, los revisaré! saludos!

**Comment by albertotb** [comment]
Ok, a ver si saco algo de tiempo para intentar al menos que funciones. Este cambio parece sencillo, esperemos que solucionar #174 no requiera muchos cambios

**Comment by gerardcl** [comment]
hola @albertotb , refactor to Rust done, check v4.0.0 if it works for you! :)
closing this issue
please, create new ones for new feature requests or issues!
Best,
