### ISSUE TITLE
Headless Chrome can't find button to trigger the search

### ISSUE THREAD

**Issue by henninggross** [gerardcl/renfe-cli#187]
**Describe the bug**
When running the CLI one runs into an error indicating that Headless Chrome wasn't able to find the button to trigger the search:

```bash
searching timetable
thread '<unnamed>' panicked at src/timetable.rs:137:10:
called `Result::unwrap()` on an `Err` value: Method call error -32000: Invalid search result range
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "foo/renfe-cli", line 8, in <module>
    sys.exit(main())
             ^^^^^^
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: Method call error -32000: Invalid search result range
``` 

They might have changed their HTML and the selector that is used isn't valid anymore.

**To Reproduce**
Run `renfe-cli -f Barc -t Mad`

**Expected behavior**
The renfe-cli doesn't panic and prints out a timetable.

**Environment (please complete the following information):**
 - OS: macOS M1
 - Version: 4.2.0

**Additional context**

**Comment by gerardcl** [comment]
nice! looks like renfe changed the site again, so that fix should handle more changes on that button! thanks a ton @henninggross !! 🚀
